repos:
  - repo: local
    hooks:
      - id: check-branch-name
        name: Check Branch Name
        entry: bash -c '[[ "$(git rev-parse --abbrev-ref HEAD)" =~ ^(feature|bugfix|hotfix)/.*$ ]]'
        language: system
        stages:
          - commit-msg

      - id: check-commit-message
        name: Check Commit Message
        entry: bash -c '[[ "$(git log -1 --pretty=%B)" =~ ^(feat|fix|docs|style|refactor|perf|test|chore):\ .+ ]]'
        language: system
        stages:
          - commit-msg
